In [1]:
import pandas as pd
import numpy as np
import pickle as pkl
import toolkit

In [120]:
with open("data/train.pkl", "rb") as file:
    df = pkl.load(file)

In [3]:
df.head()

       Status                                            Message
973         2  From OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-COM...
4592        0  Return-Path: skip@pobox.com\n.Delivery-Date: S...
13730       0  From ilug-admin@linux.ie  Fri Jul 19 23:44:22 ...
3046        2  From travelincentives@aol.com  Mon Aug  6 20:0...
6790        0  From rpm-list-admin@freshrpms.net  Wed Jul 31 ...

In [4]:
df.shape

(17416, 2)

In [5]:
domains = toolkit.extract_domain(df)

In [6]:
importants_words  = "by, ., with, 2002, the, of, -0500, to, I, a, that, it, .>, is, +0100, .Received:, ESMTP, id, by, Linux, and, .Content-Type, .Sender:, .Errors-To:, .X-Mailman-Version:, .Precedence:, bulk, .List-Id, .X-Beenthere, (Postfix), using, .Delivered-To:, or, <jm@localhost>;, -0400, IMAP, (fethmail-5.9.0), jm@localhost, (single-drop);, (IST), you, (PDT), -0700, [127.0.0.1], SMTP, (jalapeno, in, .Content-Transfer-Encoding:, will, your, email, Microsoft, its, >, our, want, <a, .<font"

In [7]:
domains[:5]

,Status,Message,s_Message,email
973,2,From OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-COM...,"[From, OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-C...",OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-COM@SMTP...
4592,0,Return-Path: skip@pobox.com .Delivery-Date: Sa...,"[Return-Path:, skip@pobox.com, .Delivery-Date:...",skip@pobox.com
13730,0,From ilug-admin@linux.ie Fri Jul 19 23:44:22 ...,"[From, ilug-admin@linux.ie, , Fri, Jul, 19, 23...",ilug-admin@linux.ie
3046,2,From travelincentives@aol.com Mon Aug 6 20:0...,"[From, travelincentives@aol.com, , Mon, Aug, ,...",travelincentives@aol.com
6790,0,From rpm-list-admin@freshrpms.net Wed Jul 31 ...,"[From, rpm-list-admin@freshrpms.net, , Wed, Ju...",rpm-list-admin@freshrpms.net

In [8]:
df = domains

In [11]:
df["email"] = df["email"].str.split("@").str[1]

In [12]:
df.head(4)

,Status,Message,s_Message,email
973,2,From OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-COM...,"[From, OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-C...",SMTP1.ADMANMAIL.COM
4592,0,Return-Path: skip@pobox.com .Delivery-Date: Sa...,"[Return-Path:, skip@pobox.com, .Delivery-Date:...",pobox.com
13730,0,From ilug-admin@linux.ie Fri Jul 19 23:44:22 ...,"[From, ilug-admin@linux.ie, , Fri, Jul, 19, 23...",linux.ie
3046,2,From travelincentives@aol.com Mon Aug 6 20:0...,"[From, travelincentives@aol.com, , Mon, Aug, ,...",aol.com

In [13]:
df["Message"] = df["s_Message"]
df.drop("s_Message", axis=1, inplace=True)

In [14]:
df.head()

,Status,s_Message,email
973,2,"[From, OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-C...",SMTP1.ADMANMAIL.COM
4592,0,"[Return-Path:, skip@pobox.com, .Delivery-Date:...",pobox.com
13730,0,"[From, ilug-admin@linux.ie, , Fri, Jul, 19, 23...",linux.ie
3046,2,"[From, travelincentives@aol.com, , Mon, Aug, ,...",aol.com
6790,0,"[From, rpm-list-admin@freshrpms.net, , Wed, Ju...",freshrpms.net

In [15]:
importants_words = importants_words.replace(" ", "").split(",")

In [19]:
df.rename({"s_Message": "Message"}, axis=1, inplace=True)

In [20]:
df.head()

,Status,Message,email
973,2,"[From, OWNER-NOLIST-SGODAILY*JM**NETNOTEINC*-C...",SMTP1.ADMANMAIL.COM
4592,0,"[Return-Path:, skip@pobox.com, .Delivery-Date:...",pobox.com
13730,0,"[From, ilug-admin@linux.ie, , Fri, Jul, 19, 23...",linux.ie
3046,2,"[From, travelincentives@aol.com, , Mon, Aug, ,...",aol.com
6790,0,"[From, rpm-list-admin@freshrpms.net, , Wed, Ju...",freshrpms.net

In [61]:
x = pd.Series(df.iloc[0, :]["Message"])

In [62]:
x = x[x != ""]

In [63]:
x.value_counts()

.                     86
to                    11
<td                   10
with                   8
you                    8
                      ..
(8.11.6/8.11.6)        1
g8P68bC14856           1
face="Arial"           1
<zzzz@jmason.org>;     1
unsubscribed.          1
Name: count, Length: 365, dtype: int64

In [66]:
word_dict = x.value_counts().to_dict()

In [65]:
series_dict = dict()

In [67]:
table = np.zeros(len(word_dict))

In [68]:
for index in range(len(importants_words)):
    count = word_dict.get(importants_words[index], 0)
    table[index] = count

In [69]:
table

array([ 5., 86.,  8.,  7.,  4.,  4.,  2., 11.,  0.,  6.,  1.,  0.,  0.,
        1.,  4.,  5.,  3.,  4.,  5.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  2.,  0.,  0.,  1.,  0.,  0.,  1.,
        2.,  8.,  0.,  0.,  1.,  1.,  1.,  4.,  0.,  0.,  2.,  2.,  0.,
        0.,  0.,  1.,  0.,  6.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.])

In [95]:
word_counts = [0 for i in range(df.shape[0])]
counter = 0
for index, row in df.iterrows():
    x = pd.Series(row["Message"])
    x = x[x != ""]
    x = x.value_counts().to_dict()

    table = np.zeros(len(importants_words), dtype=np.int16)

    for index in range(len(importants_words)):
        count = x.get(importants_words[index], 0)
        table[index] = count
    
    word_counts[counter] = table
    counter += 1

In [96]:
word_counts[:4]

[array([ 5, 86,  8,  7,  4,  4,  2, 11,  0,  6,  1,  0,  0,  1,  4,  5,  3,
         4,  5,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  2,  0,
         0,  1,  0,  0,  1,  2,  8,  0,  0,  1,  1,  1,  4,  0,  0,  2,  2,
         0,  0,  0,  1,  0,  6,  3], dtype=int16),
 array([0, 4, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16),
 array([ 5, 18,  6, 10,  9,  6,  0,  9,  6, 10,  4,  1, 10,  8,  8,  6,  5,
         5,  5,  3,  3,  0,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1,
         1,  1,  0,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0], dtype=int16),
 array([ 2, 12,  1,  0,  6,  3,  0,  3,  0,  1,  0,  0,  0,  0,  0,  2,  0,
         2,  2,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  1,  0,
         0,  0,  0,  0,  0,  0,  2,  0,  1,  0,  1,  0,  0,  0,  0,  1,  0,
         2,  0,  0,  0,  0,  0,  0], dtype=int16)]

In [97]:
counted_words = pd.DataFrame(word_counts, columns=importants_words)

In [98]:
len(importants_words)

58

In [99]:
counted_words.head()

,by,.,with,2002,the,of,-0500,to,I,a,...,will,your,email,Microsoft,its,>,our,want,<a,.<font
0,5,86,8,7,4,4,2,11,0,6,...,0,2,2,0,0,0,1,0,6,3
1,0,4,3,2,2,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,5,18,6,10,9,6,0,9,6,10,...,0,0,0,0,0,0,0,0,0,0
3,2,12,1,0,6,3,0,3,0,1,...,0,1,0,2,0,0,0,0,0,0
4,4,15,5,9,2,1,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0

In [104]:
counted_words = pd.concat([counted_words, df.drop("Message", axis=1).reset_index(drop=True)], axis=1)

In [105]:
counted_words.head()

,by,.,with,2002,the,of,-0500,to,I,a,...,>,our,want,<a,.<font,index,Status,email,Status,email
0,5,86,8,7,4,4,2,11,0,6,...,0,1,0,6,3,973,2,SMTP1.ADMANMAIL.COM,2,SMTP1.ADMANMAIL.COM
1,0,4,3,2,2,2,1,1,1,1,...,0,0,0,0,0,4592,0,pobox.com,0,pobox.com
2,5,18,6,10,9,6,0,9,6,10,...,0,0,0,0,0,13730,0,linux.ie,0,linux.ie
3,2,12,1,0,6,3,0,3,0,1,...,0,0,0,0,0,3046,2,aol.com,2,aol.com
4,4,15,5,9,2,1,0,3,0,0,...,0,0,0,0,0,6790,0,freshrpms.net,0,freshrpms.net

In [106]:
importants_words

['by',
 '.',
 'with',
 '2002',
 'the',
 'of',
 '-0500',
 'to',
 'I',
 'a',
 'that',
 'it',
 '.>',
 'is',
 '+0100',
 '.Received:',
 'ESMTP',
 'id',
 'by',
 'Linux',
 'and',
 '.Content-Type',
 '.Sender:',
 '.Errors-To:',
 '.X-Mailman-Version:',
 '.Precedence:',
 'bulk',
 '.List-Id',
 '.X-Beenthere',
 '(Postfix)',
 'using',
 '.Delivered-To:',
 'or',
 '<jm@localhost>;',
 '-0400',
 'IMAP',
 '(fethmail-5.9.0)',
 'jm@localhost',
 '(single-drop);',
 '(IST)',
 'you',
 '(PDT)',
 '-0700',
 '[127.0.0.1]',
 'SMTP',
 '(jalapeno',
 'in',
 '.Content-Transfer-Encoding:',
 'will',
 'your',
 'email',
 'Microsoft',
 'its',
 '>',
 'our',
 'want',
 '<a',
 '.<font']

In [107]:
important_words = ['by','.','with','2002','the','of','-0500','to','I','a','that','it','.>','is','+0100','.Received:','ESMTP','id','by','Linux','and','.Content-Type','.Sender:','.Errors-To:','.X-Mailman-Version:','.Precedence:','bulk', '.List-Id', '.X-Beenthere', '(Postfix)', 'using', '.Delivered-To:', 'or', '<jm@localhost>;', '-0400', 'IMAP', '(fethmail-5.9.0)', 'jm@localhost', '(single-drop);', '(IST)', 'you', '(PDT)', '-0700', '[127.0.0.1]', 'SMTP','(jalapeno','in','.Content-Transfer-Encoding:','will', 'your','email','Microsoft','its','>','our','want', '<a', '.<font']

In [108]:
len(important_words)

58

In [109]:
len(importants_words)

58

In [110]:
important_words =['by','.','with','2002','the','of','-0500','to','I','a',
                  'that','it','.>','is','+0100','.Received:','ESMTP','id',
                  'by','Linux','and','.Content-Type','.Sender:','.Errors-To:',
                  '.X-Mailman-Version:','.Precedence:','bulk', '.List-Id',
                  '.X-Beenthere', '(Postfix)', 'using', '.Delivered-To:',
                  'or', '<jm@localhost>;', '-0400', 'IMAP', '(fethmail-5.9.0)',
                  'jm@localhost','(single-drop);', '(IST)', 'you', '(PDT)', 
                  '-0700', '[127.0.0.1]', 'SMTP','(jalapeno','in',
                  '.Content-Transfer-Encoding:','will', 'your','email','Microsoft',
                  'its','>','our','want', '<a', '.<font']

In [111]:
len(important_words)

58

In [112]:
important_words == importants_words

True

In [114]:
import importlib

In [117]:
pd.concat([pd.DataFrame(word_counts, columns=important_words), df.drop("Message",axis=1).reset_index(drop=True)], 
        axis=1)

,by,.,with,2002,the,of,-0500,to,I,a,...,email,Microsoft,its,>,our,want,<a,.<font,Status,email
0,5,86,8,7,4,4,2,11,0,6,...,2,0,0,0,1,0,6,3,2,SMTP1.ADMANMAIL.COM
1,0,4,3,2,2,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,pobox.com
2,5,18,6,10,9,6,0,9,6,10,...,0,0,0,0,0,0,0,0,0,linux.ie
3,2,12,1,0,6,3,0,3,0,1,...,0,2,0,0,0,0,0,0,2,aol.com
4,4,15,5,9,2,1,0,3,0,0,...,0,0,0,0,0,0,0,0,0,freshrpms.net
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17411,6,29,6,10,0,0,0,2,0,2,...,0,0,0,0,0,0,0,0,0,linux.ie
17412,0,4,0,3,8,3,0,5,1,1,...,0,0,0,0,0,0,0,0,0,python.org
17413,19,98,13,8,108,79,0,52,2,54,...,0,0,7,0,9,0,0,0,0,xent.com
17414,7,23,9,11,1,0,0,1,0,1,...,1,0,0,0,0,0,0,0,0,redhat.com
17415,18,188,41,8,400,140,0,221,85,132,...,0,0,2,0,17,7,0,0,0,xent.com

In [118]:
importlib.reload(toolkit)

In [121]:
esss = toolkit.introductory_pipeline(df)

In [124]:
(esss == pd.concat([pd.DataFrame(word_counts, columns=important_words), df.drop("Message",axis=1).reset_index(drop=True)], axis=1))

,by,.,with,2002,the,of,-0500,to,I,a,...,email,Microsoft,its,>,our,want,<a,.<font,Status,domain
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17411,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17412,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17413,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17414,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17415,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True