In [1]:
import pandas as pd
import pickle as pkl

In [2]:
with open("data/test.pkl", "rb") as file:
    test = pkl.load(file)

with open("data/train.pkl", "rb") as file:
    train = pkl.load(file)

In [3]:
test.head()

       Status                                            Message
11066       1  Return-Path: <owner-nessus@list.nessus.org>\n....
9725        0  From ilug-admin@linux.ie  Fri Aug  2 10:06:30 ...
12351       0  From rpm-list-admin@freshrpms.net  Mon Sep 30 ...
12458       0  From rpm-list-admin@freshrpms.net  Thu Oct 10 ...
12448       0  From rpm-list-admin@freshrpms.net  Tue Oct  8 ...

In [4]:
train.head()

       Status                                            Message
6990        0  From fork-admin@xent.com  Tue Aug 20 22:15:08 ...
10929       1  Return-Path: <Online#3.19700.89-xNOclp13QVGIDs...
12984       0  From rssfeeds@jmason.org  Tue Sep 24 10:47:34 ...
3888        0  From exmh-users-admin@redhat.com  Thu Sep 12 1...
9491        0  From sentto-2242572-60407-1039000218-jm=jmason...

In [5]:
train.shape, test.shape

((8856, 2), (2953, 2))

In [6]:
X = pd.concat([train, test])

In [7]:
X.shape

(11809, 2)

In [8]:
s = X["Message"]

In [9]:
s[:1]

6990    From fork-admin@xent.com  Tue Aug 20 22:15:08 ...
Name: Message, dtype: object

In [10]:
s.unique().shape

(11809,)

In [11]:
Z = X.drop_duplicates()

In [12]:
Z.shape

(11809, 2)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
train, test = train_test_split(Z, stratify=Z["Status"], test_size=0.1)

In [15]:
with open("data/train.pkl", "wb") as file:
    pkl.dump(train, file)

In [16]:
with open("data/test.pkl", "wb") as file:
    pkl.dump(test, file)

In [17]:
test.shape

(1181, 2)

In [18]:
train.shape

(10628, 2)