In [1]:
import pandas as pd
import numpy as np
import pickle as pkl
import toolkit

In [2]:
with open("data/train.pkl", "rb") as file:
    df = pkl.load(file)

In [3]:
df.head()

       Status                                            Message
2870        0  From ilug-admin@linux.ie  Thu Aug 29 16:42:34 ...
13153       0  From rssfeeds@jmason.org  Thu Sep 26 16:43:26 ...
4278        0  From spamassassin-talk-admin@lists.sourceforge...
4038        2  From jm@netnoteinc.com  Mon Jul 29 11:22:06 20...
774         0  From fork-admin@xent.com  Mon Sep 23 15:00:49 ...

In [4]:
df.shape

(10628, 2)

In [5]:
domains = toolkit.extract_domain(df)

In [6]:
importants_words  = toolkit.important_words

In [7]:
domains[:5]

,Status,Message,s_Message,email
2870,0,From ilug-admin@linux.ie Thu Aug 29 16:42:34 ...,"[From, ilug-admin@linux.ie, , Thu, Aug, 29, 16...",ilug-admin@linux.ie
13153,0,From rssfeeds@jmason.org Thu Sep 26 16:43:26 ...,"[From, rssfeeds@jmason.org, , Thu, Sep, 26, 16...",rssfeeds@jmason.org
4278,0,From spamassassin-talk-admin@lists.sourceforge...,"[From, spamassassin-talk-admin@lists.sourcefor...",spamassassin-talk-admin@lists.sourceforge.net
4038,2,From jm@netnoteinc.com Mon Jul 29 11:22:06 20...,"[From, jm@netnoteinc.com, , Mon, Jul, 29, 11:2...",jm@netnoteinc.com
774,0,From fork-admin@xent.com Mon Sep 23 15:00:49 ...,"[From, fork-admin@xent.com, , Mon, Sep, 23, 15...",fork-admin@xent.com

In [8]:
df = domains

In [9]:
df["email"] = df["email"].str.split("@").str[1]

In [10]:
df.head(4)

,Status,Message,s_Message,email
2870,0,From ilug-admin@linux.ie Thu Aug 29 16:42:34 ...,"[From, ilug-admin@linux.ie, , Thu, Aug, 29, 16...",linux.ie
13153,0,From rssfeeds@jmason.org Thu Sep 26 16:43:26 ...,"[From, rssfeeds@jmason.org, , Thu, Sep, 26, 16...",jmason.org
4278,0,From spamassassin-talk-admin@lists.sourceforge...,"[From, spamassassin-talk-admin@lists.sourcefor...",lists.sourceforge.net
4038,2,From jm@netnoteinc.com Mon Jul 29 11:22:06 20...,"[From, jm@netnoteinc.com, , Mon, Jul, 29, 11:2...",netnoteinc.com

In [11]:
df["Message"] = df["s_Message"]
df.drop("s_Message", axis=1, inplace=True)

In [12]:
df.head()

,Status,Message,email
2870,0,"[From, ilug-admin@linux.ie, , Thu, Aug, 29, 16...",linux.ie
13153,0,"[From, rssfeeds@jmason.org, , Thu, Sep, 26, 16...",jmason.org
4278,0,"[From, spamassassin-talk-admin@lists.sourcefor...",lists.sourceforge.net
4038,2,"[From, jm@netnoteinc.com, , Mon, Jul, 29, 11:2...",netnoteinc.com
774,0,"[From, fork-admin@xent.com, , Mon, Sep, 23, 15...",xent.com

In [15]:
df.rename({"s_Message": "Message"}, axis=1, inplace=True)

In [16]:
df.head()

,Status,Message,email
2870,0,"[From, ilug-admin@linux.ie, , Thu, Aug, 29, 16...",linux.ie
13153,0,"[From, rssfeeds@jmason.org, , Thu, Sep, 26, 16...",jmason.org
4278,0,"[From, spamassassin-talk-admin@lists.sourcefor...",lists.sourceforge.net
4038,2,"[From, jm@netnoteinc.com, , Mon, Jul, 29, 11:2...",netnoteinc.com
774,0,"[From, fork-admin@xent.com, , Mon, Sep, 23, 15...",xent.com

In [17]:
x = pd.Series(df.iloc[0, :]["Message"])

In [18]:
x = x[x != ""]

In [19]:
x.value_counts()

.                                             20
.>                                            14
29                                             9
Aug                                            9
2002                                           9
                                              ..
.--                                            1
.Irish                                         1
.http://www.linux.ie/mailman/listinfo/ilug     1
information.                                   1
.List                                          1
Name: count, Length: 243, dtype: int64

In [20]:
word_dict = x.value_counts().to_dict()

In [21]:
series_dict = dict()

In [22]:
table = np.zeros(len(word_dict))

In [23]:
for index in range(len(importants_words)):
    count = word_dict.get(importants_words[index], 0)
    table[index] = count

In [24]:
table

array([20., 14.,  9.,  9.,  7.,  7.,  7.,  5.,  5.,  4.,  4.,  4.,  3.,
        3.,  3.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [25]:
word_counts = [0 for i in range(df.shape[0])]
counter = 0
for index, row in df.iterrows():
    x = pd.Series(row["Message"])
    x = x[x != ""]
    x = x.value_counts().to_dict()

    table = np.zeros(len(importants_words), dtype=np.int16)

    for index in range(len(importants_words)):
        count = x.get(importants_words[index], 0)
        table[index] = count
    
    word_counts[counter] = table
    counter += 1

In [26]:
word_counts[:4]

[array([20, 14,  9,  9,  7,  7,  7,  5,  5,  4,  4,  4,  3,  3,  3,  3,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0], dtype=int16),
 array([6, 0, 5, 0, 3, 3, 3, 3, 0, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 0, 0, 0, 1, 1,
        0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int16),
 array([21,  9, 11,  2,  8,  8,  8,  4,  2,  3,  4,  6,  2,  1,  0,  6,  1,
         5,  4,  2,  0,  0,  0,  1,  1,  2,  4,  0,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  1,
         1,  1,  1,  1,  1,  1,  0,  0,  1,  0,  1,  0,  1,  0,  4,  2,  2,
         2,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0], dtype=int16),
 array([35,  0,  6, 12,  5,  6,  4,  2,  5,  4,  2,  1,  1,  0,  7,  9,  0,
         0,  1,  0,  0,  0,  3,  1,  1,  2,  1,  2,  2,  1,  1,  1,  1,  1,
         0,  0,  1,  1,  0,  0,  0,  3,  3,  1,  1,  1,  1,  0,  3,  3,  0,
         0,  0,  0,  0,  0,  7,  6,  3,  2,  0,  1,  0,  1,  0,  3,  0,  0,
         0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  1,  3,  1,  0,  0,  0, 12,
        10], dtype=int16)]

In [27]:
counted_words = pd.DataFrame(word_counts, columns=importants_words)

In [28]:
len(importants_words)

86

In [29]:
counted_words.head()

,.,.>,2002,the,from,with,.Received:,+0100,a,for,...,e-mail,had,.Reply-To:,our,<a,.<table,We,/>,.<td,Helvetica
0,20,14,9,9,7,7,7,5,5,4,...,0,0,0,0,0,0,0,0,0,0
1,6,0,5,0,3,3,3,3,0,1,...,0,0,0,0,0,0,0,0,0,0
2,21,9,11,2,8,8,8,4,2,3,...,0,0,0,0,0,0,0,0,0,0
3,35,0,6,12,5,6,4,2,5,4,...,0,0,1,3,1,0,0,0,12,10
4,16,0,8,1,6,5,6,3,1,4,...,0,0,0,0,0,0,0,0,0,0

In [30]:
counted_words = pd.concat([counted_words, df.drop("Message", axis=1).reset_index(drop=True)], axis=1)

In [31]:
counted_words.head()

,.,.>,2002,the,from,with,.Received:,+0100,a,for,...,.Reply-To:,our,<a,.<table,We,/>,.<td,Helvetica,Status,email
0,20,14,9,9,7,7,7,5,5,4,...,0,0,0,0,0,0,0,0,0,linux.ie
1,6,0,5,0,3,3,3,3,0,1,...,0,0,0,0,0,0,0,0,0,jmason.org
2,21,9,11,2,8,8,8,4,2,3,...,0,0,0,0,0,0,0,0,0,lists.sourceforge.net
3,35,0,6,12,5,6,4,2,5,4,...,1,3,1,0,0,0,12,10,2,netnoteinc.com
4,16,0,8,1,6,5,6,3,1,4,...,0,0,0,0,0,0,0,0,0,xent.com

In [32]:
importants_words

['.',
 '.>',
 '2002',
 'the',
 'from',
 'with',
 '.Received:',
 '+0100',
 'a',
 'for',
 'id',
 'by',
 'ESMTP',
 'Linux',
 'you',
 'to',
 '[127.0.0.1]',
 'I',
 'it',
 '-0000',
 'Microsoft',
 'my',
 'that',
 'have',
 '[127.0.0.1])',
 'localhost',
 'on',
 'SMTP',
 'be',
 '(Postfix)',
 '(localhost',
 '.Delivered-To:',
 '(single-drop);',
 '(fetchmail-5.9.0)',
 'IMAP',
 'phobos',
 '(IST)',
 '(8.11.6/8.11.6)',
 'dogma.slashnull.org',
 '.X-Priority:',
 '7bit',
 '.Content-Transfer-Encoding:',
 '.Content-Type:',
 'text/plain;',
 '1.0',
 '.MIME-Version:',
 '.Date:',
 '.Errors-To:',
 'will',
 'of',
 '.X-Beenthere:',
 '.X-Mailman-Version:',
 'bulk',
 '.List-Id:',
 '.Precedence:',
 '.Sender:',
 'and',
 'your',
 'can',
 'or',
 '--',
 '<jm@localhost>;',
 'jalapeno',
 'jm@localhost',
 '(jalapeno',
 'this',
 'but',
 '#1',
 '-0700',
 'than',
 'was',
 'email',
 'fork-admin@xent.com',
 'xent.com',
 '(PDT)',
 'his',
 'e-mail',
 'had',
 '.Reply-To:',
 'our',
 '<a',
 '.<table',
 'We',
 '/>',
 '.<td',
 'Helvetica']

In [33]:
important_words = ['by','.','with','2002','the','of','-0500','to','I','a','that','it','.>','is','+0100','.Received:','ESMTP','id','by','Linux','and','.Content-Type','.Sender:','.Errors-To:','.X-Mailman-Version:','.Precedence:','bulk', '.List-Id', '.X-Beenthere', '(Postfix)', 'using', '.Delivered-To:', 'or', '<jm@localhost>;', '-0400', 'IMAP', '(fethmail-5.9.0)', 'jm@localhost', '(single-drop);', '(IST)', 'you', '(PDT)', '-0700', '[127.0.0.1]', 'SMTP','(jalapeno','in','.Content-Transfer-Encoding:','will', 'your','email','Microsoft','its','>','our','want', '<a', '.<font']

In [34]:
len(important_words)

58

In [40]:
len(importants_words)

86

In [36]:
import importlib

In [39]:
word_counts[0].shape

(86,)

In [41]:
pd.concat([pd.DataFrame(word_counts, columns=importants_words), df.drop("Message",axis=1).reset_index(drop=True)], 
        axis=1)

,.,.>,2002,the,from,with,.Received:,+0100,a,for,...,.Reply-To:,our,<a,.<table,We,/>,.<td,Helvetica,Status,email
0,20,14,9,9,7,7,7,5,5,4,...,0,0,0,0,0,0,0,0,0,linux.ie
1,6,0,5,0,3,3,3,3,0,1,...,0,0,0,0,0,0,0,0,0,jmason.org
2,21,9,11,2,8,8,8,4,2,3,...,0,0,0,0,0,0,0,0,0,lists.sourceforge.net
3,35,0,6,12,5,6,4,2,5,4,...,1,3,1,0,0,0,12,10,2,netnoteinc.com
4,16,0,8,1,6,5,6,3,1,4,...,0,0,0,0,0,0,0,0,0,xent.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10623,16,0,8,0,6,6,6,3,3,9,...,0,0,0,0,0,0,0,0,0,xent.com
10624,23,0,6,16,6,4,4,3,7,4,...,0,1,0,0,2,0,0,11,2,chel.elektra.ru
10625,19,0,8,32,6,11,6,3,10,6,...,0,0,0,0,0,0,0,0,0,xent.com
10626,16,0,9,3,7,6,7,3,0,3,...,0,0,0,0,0,0,0,0,0,xent.com
10627,9,0,5,0,3,3,3,3,2,1,...,0,0,0,0,0,0,0,0,0,jmason.org

In [42]:
importlib.reload(toolkit)

In [45]:
with open("data/train.pkl", "rb") as file:
    df = pkl.load(file)
df.head()

       Status                                            Message
2870        0  From ilug-admin@linux.ie  Thu Aug 29 16:42:34 ...
13153       0  From rssfeeds@jmason.org  Thu Sep 26 16:43:26 ...
4278        0  From spamassassin-talk-admin@lists.sourceforge...
4038        2  From jm@netnoteinc.com  Mon Jul 29 11:22:06 20...
774         0  From fork-admin@xent.com  Mon Sep 23 15:00:49 ...

In [46]:
esss = toolkit.introductory_pipeline(df)

In [49]:
esss.shape

(10628, 88)

In [54]:
(esss.iloc[:, :-1] == pd.concat([pd.DataFrame(word_counts, columns=importants_words), df.drop("Message",axis=1).reset_index(drop=True)], axis=1).iloc[:, :-1]).all().all()

np.True_